---
dataset: "SST2"
computer: "labo"
dataset_size: 0
random_seed: 42
max_length: 0
algo: "AE"
encoder: "GRU"
decoder: "GRU"
nb_epoch: 4
latent_size: 4096 #15
hidden_size: 1024
embedd_size: 300
num_layers: 1
batch_size: 64
dropout: 0.3
word_dropout: 0
x0: 15
