---
dataset: "SST2"
computer: "labo"
dataset_size: 0
random_seed: 42
max_length: 0
algo: "VAE_Annealing_Reg"
encoder: "GRU"
decoder: "GRU"
nb_epoch: 30
latent_size: 15
hidden_size: 512
embedd_size: 300
num_layers: 1
batch_size: 64
dropout: 0.3
word_dropout: 0.3
x0: 15
k: 0.025

min_z: 3