---
dataset: "SST2"
computer: "labo"
dataset_size: 0
random_seed: 42
max_length: 0
algo: "WSVAE"
encoder: "GRU"
decoder: "GRU"
discriminator: "GRU"
nb_epoch: 1 #30
nb_epoch_discriminator: 1
nb_epoch_fine_tuning: 1 #5
latent_size: 15
hidden_size: 1024
embedd_size: 300
num_layers: 1
batch_size: 64
dropout: 0.3
word_dropout: 0.3
x0: 15
num_classes: 2